### PR TITLE
Adds MihiraTheTiger and Whatevs4

### PR DESCRIPTION
**Pull request by Whatevs4**

### CODE REVIEW

**Comment by Whatevs4** [comment]
In Mihira's Yiff Yiff attack I used 1-4 instead of 0-3 for the values 'bawked' could take (since it's generated by this.random(4)). Could you fix this? Also, I think we should probably buff the secondary chance of Yiff Yiff to 10 or 20 or even 30% since Mihira's not going to be very competitive without reasonably reliable buffs.

**Comment by Whatevs4** [comment]
Furrier Coat doesn't increase spd at all and I have no idea why. BibleThump
It looks like the code is right, the only possible explanation is that onModifySpd is not a valid code. Haaaalp!

**Comment by Whatevs4** [comment]
Azum pointed out that it's because I spelled Priority wrong in the code onModifySpdPriority. Be a doll and fix this? I need to spellcheck more carefully. DansGame

**Comment by TieSoul** [comment]
BloodTrail

**Pull request merged**
